# Whale you be my container?
#
# VERSION       0.42

# use the base image provided by Docker
FROM base

MAINTAINER Moby Dock victor.coisne@docker.com

# say hello when the container is launched
ENTRYPOINT echo "Whale you be my container"
